# Generated by Django 6.0.2 on 2026-02-22 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=100)),
                ('excerpt', models.TextField()),
                ('read_time', models.CharField(max_length=50)),
                ('published_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('p', 'Paragraph'), ('h2', 'Heading 2'), ('code', 'Code')], max_length=10)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='core.post')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('site', models.URLField(blank=True)),
                ('youtube', models.CharField(blank=True, max_length=100)),
                ('thumbnail', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stack', models.ManyToManyField(blank=True, to='core.skill')),
            ],
        ),
    ]
